### ISSUE TITLE
Can't get the default configuration to work

### ISSUE THREAD

**Issue by Sh1d0w** [spiral/roadrunner-broadcast#15]
Hi, and thanks for the great ecosystem!

I am having a trouble getting the broadcast plugin to work. I've followed the example:

```
websockets:
    broker: default
    path: "/ws"

broadcast:
    default:
        driver: memory
        config: {}
```

Then I have

```
$rpc = \Spiral\Goridge\RPC\RPC::create('tcp://127.0.0.1:6001');
$broadcast = new Broadcast($rpc);
$broadcast->publish('channel-1', 'message for channel #1');
```

But in the logs I can see

```
backend-payments-1  | 2022-09-14T06:16:11.349Z	DEBUG	broadcast   	message was published	{"msg": "messages:{topics:\"channel-1\" payload:\"message for channel #1\"}"}
backend-payments-1  | 2022-09-14T06:16:11.349Z	WARN	broadcast   	no publishers was registered
```

From what I can see the error is triggered here

https://github.com/roadrunner-server/broadcast/blob/master/plugin.go#L99

Which can only happen if there are no registered publishers. They re registered by the method call of GetDriver, but for Gods love, I didn't find anywhere this method to be called, neither in endure or roadrunner, so not sure how to proceed to resolve the issue.

**Comment by Sh1d0w** [comment]
@rustatian would appreciate some advice where I am doing it wrong 😀

**Comment by Sh1d0w** [comment]
Ok I got it where is is called it is here https://github.com/roadrunner-server/websockets/blob/master/plugin.go#L116

But I still don't have no idea why it  is not working, I don't see any errors in the logs about the configuration.

**Comment by rustatian** [comment]
Hey @Sh1d0w 👋🏻 
Interesting... I looked at the tests and saw that I have a similar config to yours, and it's working.

**Comment by Sh1d0w** [comment]
@rustatian It was my mistake I've figured it out. The broker registration was happening in the Serve method, which I believe is when you are using the HTTP plugin and have active web socket opened.

**Comment by rustatian** [comment]
Have you added the `websockets` middleware to the list of the `HTTP` middleware?

**Comment by Sh1d0w** [comment]
Yes I did and it is all good now, thanks and sorry for disturbing you :)

**Comment by rustatian** [comment]
No problem at all 😃 Enjoy RR+Spiral ❤️

**Comment by rustatian** [comment]
@Sh1d0w You may also join our discord server: https://discord.gg/TFeEmCs
(if you would have a question or wanted to discuss smt)
